// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVfN6bOlqA1OBjW7daAxnwZ8h8JASciik',
    appId: '1:722650764454:web:8cb6eff9ce076ad0805067',
    messagingSenderId: '722650764454',
    projectId: 'freshtrack-40a03',
    authDomain: 'freshtrack-40a03.firebaseapp.com',
    storageBucket: 'freshtrack-40a03.firebasestorage.app',
    measurementId: 'G-S26DV3HF6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRKbw1SspSQIOhZlw2_T3LlzJ7Qw8fh7E',
    appId: '1:722650764454:android:1966f605e617b60f805067',
    messagingSenderId: '722650764454',
    projectId: 'freshtrack-40a03',
    storageBucket: 'freshtrack-40a03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUuF9bV-AMY4Ig6PnJHmoUDQ9bHflCY8',
    appId: '1:722650764454:ios:330feca491cff04b805067',
    messagingSenderId: '722650764454',
    projectId: 'freshtrack-40a03',
    storageBucket: 'freshtrack-40a03.firebasestorage.app',
    iosBundleId: 'com.example.freshtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUuF9bV-AMY4Ig6PnJHmoUDQ9bHflCY8',
    appId: '1:722650764454:ios:330feca491cff04b805067',
    messagingSenderId: '722650764454',
    projectId: 'freshtrack-40a03',
    storageBucket: 'freshtrack-40a03.firebasestorage.app',
    iosBundleId: 'com.example.freshtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVfN6bOlqA1OBjW7daAxnwZ8h8JASciik',
    appId: '1:722650764454:web:f19e957537496784805067',
    messagingSenderId: '722650764454',
    projectId: 'freshtrack-40a03',
    authDomain: 'freshtrack-40a03.firebaseapp.com',
    storageBucket: 'freshtrack-40a03.firebasestorage.app',
    measurementId: 'G-FJSGJ9NXKJ',
  );
}
